FROM phusion/baseimage:0.9.18

RUN apt-get update && \
  apt-get install -y software-properties-common && \
  apt-add-repository -y ppa:ansible/ansible && \
  apt-get update && \
  apt-get install -y ansible python-pip curl unzip jq vim

RUN pip install boto

RUN mkdir -p /opt/ee
RUN mkdir -p /etc/ansible

WORKDIR /opt/ee

VOLUME /etc/conjur

ENV TERM xterm

# Enable a service to keep the container running.
RUN rm /etc/service/sshd/down
