FROM phusion/baseimage:0.9.18

RUN apt-get update && \
  apt-get install -y software-properties-common && \
  apt-add-repository -y ppa:ansible/ansible && \
  apt-get update && \
  apt-get install -y ansible python-pip curl unzip jq vim

RUN pip install boto

ADD admin /src/

WORKDIR /src
